apiVersion: v1
kind: Namespace
metadata:
 name: default
 ---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: service
 namespace: default
spec:
replicas: 2
template:
 metadata:
  labels:
   app: service
 spec:
  containers:
  - image: aksdemoconreg.azurecr.io/service:20191223.2
    name: service
    ports:
    - containerPort: 8080
    imagePullSecrets:
    - name: acrsecret
---
apiVersion: v1
kind: Service
metadata:
 name: service
 namespace: #{Release.EnvironmentName}#
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: service
 type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: service
 annotations:
  kubernetes.io/ingress.class: addon-http-application-routing
spec:
 rules:
 - host: service.405bb2c6ff9540e2b186.westeurope.aksapp.io
   http:
    paths:
    - backend:
       serviceName: service
       servicePort: 80
      path: /
  
  
 
 
  
